/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d8dadc',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#ffb596',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-primary-fixed-variant': '#003ea8',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'outline-variant': '#c3c6d7',
        outline: '#737686',
        'surface-tint': '#0053db',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'surface-container-low': '#f2f4f6',
        'on-secondary-fixed-variant': '#005236',
        'secondary-container': '#6cf8bb',
        'on-background': '#191c1e',
        'inverse-primary': '#b4c5ff',
        'tertiary-container': '#bc4800',
        'tertiary-fixed': '#ffdbcd',
        'surface-container-highest': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        'surface-container': '#eceef0',
        'primary-container': '#2563eb',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-container': '#ffede6',
        'on-error': '#ffffff',
        'surface-variant': '#e0e3e5',
        primary: '#004ac6',
        'on-primary-container': '#eeefff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#360f00',
        'on-primary': '#ffffff',
        tertiary: '#943700',
        secondary: '#006c49',
        'on-surface-variant': '#434655',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        background: '#f7f9fb',
        'on-tertiary-fixed-variant': '#7d2d00',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      boxShadow: {
        ambient: '0 0 40px rgba(25, 28, 30, 0.06)',
        card: '0 8px 30px rgba(148, 163, 184, 0.12)',
      },
    },
  },
  plugins: [],
}
